language: java
install: true

jdk:
- openjdk8

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

script:
  - ./gradlew buildPlugin

deploy:
  provider: releases
  cleanup: false
  file: "build/distributions/*"
  api_key: "$API_KEY"
  on:
    tags: false #发布  tag版 时才进行发包